use std::collections::VecDeque;
use std::fmt;
use std::io::Cursor;

use serde::{Deserialize, Serialize};

pub type NodeId = u64;

/// Addresses replicated as part of Raft membership.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ControllerNode {
    /// Base URL at which the internal Raft router is mounted.
    pub raft_url: String,
    /// Public Swarmlite controller URL used for client redirects.
    pub api_url: String,
}

impl fmt::Display for ControllerNode {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{} ({})", self.api_url, self.raft_url)
    }
}

/// A deterministic mutation of the replicated control-plane value.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum Command {
    /// Replace the opaque application value when `expected_generation` still
    /// matches. Random IDs and timestamps belong inside `value`, generated by
    /// the leader before this command is submitted.
    Replace {
        request_id: String,
        expected_generation: u64,
        value: Vec<u8>,
    },
}

impl Command {
    pub fn request_id(&self) -> &str {
        match self {
            Self::Replace { request_id, .. } => request_id,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CommandResponse {
    pub request_id: String,
    pub generation: u64,
    pub outcome: CommandOutcome,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CommandOutcome {
    Applied,
    Conflict,
    Ignored,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct ReplicatedState {
    pub generation: u64,
    pub value: Vec<u8>,
}

pub(crate) const DEDUP_WINDOW: usize = 2_048;

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub(crate) struct ApplicationState {
    pub current: ReplicatedState,
    #[serde(skip, default)]
    pub recent_responses: VecDeque<(String, CommandResponse)>,
}

impl ApplicationState {
    pub(crate) fn apply(&mut self, command: Command) -> CommandResponse {
        if let Some((_, response)) = self
            .recent_responses
            .iter()
            .find(|(request_id, _)| request_id == command.request_id())
        {
            return response.clone();
        }

        let response = match command {
            Command::Replace {
                request_id,
                expected_generation,
                value,
            } => {
                let outcome = if expected_generation == self.current.generation {
                    self.current.generation += 1;
                    self.current.value = value;
                    CommandOutcome::Applied
                } else {
                    CommandOutcome::Conflict
                };
                CommandResponse {
                    request_id,
                    generation: self.current.generation,
                    outcome,
                }
            }
        };

        self.recent_responses
            .push_back((response.request_id.clone(), response.clone()));
        while self.recent_responses.len() > DEDUP_WINDOW {
            self.recent_responses.pop_front();
        }
        response
    }
}

openraft::declare_raft_types!(
    pub TypeConfig:
        D = Command,
        R = CommandResponse,
        NodeId = NodeId,
        Node = ControllerNode,
);

pub type Entry = openraft::Entry<TypeConfig>;
pub type Raft = openraft::Raft<TypeConfig>;

pub type ClientWriteError = openraft::error::ClientWriteError<NodeId, ControllerNode>;
pub type ClientWriteRaftError = openraft::error::RaftError<NodeId, ClientWriteError>;
pub type CheckIsLeaderError = openraft::error::CheckIsLeaderError<NodeId, ControllerNode>;
pub type CheckIsLeaderRaftError = openraft::error::RaftError<NodeId, CheckIsLeaderError>;
pub type InitializeError = openraft::error::InitializeError<NodeId, ControllerNode>;
pub type InitializeRaftError = openraft::error::RaftError<NodeId, InitializeError>;
pub type RpcError<E = openraft::error::Infallible> =
    openraft::error::RPCError<NodeId, ControllerNode, openraft::error::RaftError<NodeId, E>>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn applies_with_generation_cas_and_deduplicates() {
        let mut state = ApplicationState::default();
        let command = Command::Replace {
            request_id: "request-1".into(),
            expected_generation: 0,
            value: b"one".to_vec(),
        };
        let first = state.apply(command.clone());
        let duplicate = state.apply(command);
        assert_eq!(first.outcome, CommandOutcome::Applied);
        assert_eq!(first, duplicate);
        assert_eq!(state.current.generation, 1);

        let conflict = state.apply(Command::Replace {
            request_id: "request-2".into(),
            expected_generation: 0,
            value: b"stale".to_vec(),
        });
        assert_eq!(conflict.outcome, CommandOutcome::Conflict);
        assert_eq!(state.current.value, b"one");
    }

    #[test]
    fn request_deduplication_history_is_not_durable() {
        let mut state = ApplicationState::default();
        state.apply(Command::Replace {
            request_id: "request-1".into(),
            expected_generation: 0,
            value: b"one".to_vec(),
        });

        let encoded = serde_json::to_vec(&state).unwrap();
        assert!(!String::from_utf8_lossy(&encoded).contains("recent_responses"));
        let restored: ApplicationState = serde_json::from_slice(&encoded).unwrap();
        assert_eq!(restored.current, state.current);
        assert!(restored.recent_responses.is_empty());
    }
}
