version: "3.8"

services:
  web:
    image: nginx:1.29-alpine
    stop_grace_period: 20s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ >/dev/null"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 3s
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.role==app
      update_config:
        parallelism: 1
        order: start-first
      labels:
        swarmlite.ingress.enable: "true"
        swarmlite.ingress.host: example.com
        swarmlite.ingress.port: "80"
