[package]
name = "swarmlite-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
swarmlite-client.workspace = true
swarmlite-core.workspace = true
swarmlite-node.workspace = true
swarmlite-platform.workspace = true
swarmlite-protocol.workspace = true
swarmlite-registry.workspace = true
swarmlite-stack.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
